const habitConstants = {
  RETRIEVE_ALL_SUCCESS: "RETRIEVE_ALL_SUCCESS",
  RETRIEVE_ALL_ERROR: "RETRIEVE_ALL_ERROR",

  CREATE_SUCCESS: "CREATE_HABIT_SUCCESS",
  EDIT_SUCCESS: "EDIT_HABIT_SUCCESS",
  DELETE_SUCCESS: "DELETE_SUCCESS",
}

export default habitConstants;